name = "AcronymGenerator"
uuid = "6f5473c6-cf97-496f-b9a6-ddb5452e73f0"
authors = ["Jared Lumpe"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
